**1) Tulis program NumPy untuk membuat array berisi 10 element bernilai
nol, 10 element bernilai satu, dan 10 element bernilai lima.**

**Jawab**
* Seluruh program menggunakan numpy methode 

In [170]:
import numpy as np 

* Membuat array dengan vektor 1 dimensi terdiri 10 elemen, dengan nilai elemen adalah 0

In [171]:
a = np.zeros ((1,10))
print (a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


* Membuat array dengan vektor 1 dimensi terdiri 10 elemen, dengan nilai elemen adalah 1

In [172]:
b = np.ones((1,10))
print (b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


* Membuat array dengan vektor 1 dimensi terdiri 10 elemen, dengan nilai elemen adalah 5
* Menggunakan metode full untuk mengisi setiap elemen array
* full ((row,col),value)

In [173]:
c = np.full((1,10), (5))
c

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

* menggabungkan ketiga array ke dalam 1 array

In [174]:
num_ = np.array ((a,b,c))
print (num_)
print (type(num_))


[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]]
<class 'numpy.ndarray'>


**2) Tulis program NumPy untuk membuat vektor dengan panjang 10 element dengan nilai yang didistribusikan secara merata antara 5 dan 50.**

**Jawab**
* Menggunakan metode linspace untuk membagi rata nilai pada array dalam suatu range.
* Linspace merupakan fungsi yang mengembalikan baris yang berisi nilai dengan sejumlah elemen dengan jarak yang saya untuk suatu rentang. 

In [175]:
a3 = np.linspace(5,50,10)

In [176]:
a3

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

* mengecek jumlah elemen dari array a3
* elemen a3 berisi sebanyak 10 elemen 

In [177]:
a3.size

10

**3) Tulis program NumPy untuk mendapatkan elemen unik dari array.**

**Jawab**
* Menggunakan metode unique untuk mendapatkan nilai unik dari sebuah array

In [178]:
a4 = np.unique(a3)
print (a4)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


* Pembuatan array dengan metode yang lain, kemudian diambil unique value untuk menghasilkan array baru

In [179]:
a5 = np.random.randint (15, size = (3,5))
a5

array([[ 5,  3, 11,  6,  7],
       [ 2,  1,  1,  7,  3],
       [ 3,  4, 10,  5,  2]])

In [180]:
aa= np.unique (a5)
print (aa)
print (type(aa))

[ 1  2  3  4  5  6  7 10 11]
<class 'numpy.ndarray'>


In [181]:
a_ = [ 1,1,4,5,7,9,11,23,22,33,1,2]
aa_ = np.array(a_)
aa_

array([ 1,  1,  4,  5,  7,  9, 11, 23, 22, 33,  1,  2])

In [182]:
ab= np.unique(aa_)
ab

array([ 1,  2,  4,  5,  7,  9, 11, 22, 23, 33])

**4) Tulis program NumPy untuk menemukan indeks dari nilai maksimum
dan minimum di sepanjang array yang diberikan.**

**Jawab**
* Menggunakan metode min dan max sebagai pilihan untuk menemukan nilai minimun dan maksimum di sepanjang 
  array yang diberikan.
* hal ini mengambil nilai min dan max dari array a3, dengan nilai antara 5 dan 50

In [183]:
ac = np.min(a3)
ac

5.0

In [184]:
ac_ = np.max (a3)
ac_ 

50.0

In [185]:
print (ac, ac_)

5.0 50.0


* Menggunakan fungsi keyword def untuk mengambil nilai minimum dan maksimum secara bersamaan dari sebuah array

In [186]:
def n_max(deret_bilangan):
    n_max = deret_bilangan[0]

    for n in deret_bilangan:
        if n > nilai_terbesar:
             nilai_terbesar = n

    return nilai_terbesar

def n_min(deret_bilangan):
    n_min = deret_bilangan[0]

    for n in deret_bilangan:
        if n < nilai_terkecil:
             nilai_terkecil = n

    return nilai_terkecil

In [187]:
print (a3)
print (nilai_minimal(a3))
print (nilai_maksimal(a3))

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]
5.0
50.0


In [188]:
min(a3), max(a3)

(5.0, 50.0)

**5) Tulis program NumPy untuk membulatkan elemen array ke jumlah
desimal yang diberikan.**

**Jawab**
* Membuat array secara random dengan nilai elemen berisi desimal dengan 8 angka desimal
* Kemudian membulatkan elemen menjadi 2 angka desimal
* Menggunakan metode rounding (pembulatan) sebagai pilihan untuk membulatkan nilai desimal sebuah array.
* Around merupakan fungsi untuk menaikkan digit atau desimal sebelumnya sebesar 1 jika >= 5.

In [189]:
a5 = np.random.random(20)
a5

array([0.52372527, 0.2631821 , 0.89238297, 0.38075977, 0.02042997,
       0.23010535, 0.98729767, 0.58541408, 0.21997369, 0.63712178,
       0.97233457, 0.5130355 , 0.27931295, 0.06175911, 0.32593641,
       0.78416564, 0.4203336 , 0.71066843, 0.55237197, 0.50531843])

In [190]:
a6= np.around(a5,2)
a6

array([0.52, 0.26, 0.89, 0.38, 0.02, 0.23, 0.99, 0.59, 0.22, 0.64, 0.97,
       0.51, 0.28, 0.06, 0.33, 0.78, 0.42, 0.71, 0.55, 0.51])

* Membuat array secara acak denga nilai elemen antara 1 hingga 5 dengan nilai distribusi merata sebesar 0.069

In [191]:
a5_ = np.arange (1,5,0.069)
a5_

array([1.   , 1.069, 1.138, 1.207, 1.276, 1.345, 1.414, 1.483, 1.552,
       1.621, 1.69 , 1.759, 1.828, 1.897, 1.966, 2.035, 2.104, 2.173,
       2.242, 2.311, 2.38 , 2.449, 2.518, 2.587, 2.656, 2.725, 2.794,
       2.863, 2.932, 3.001, 3.07 , 3.139, 3.208, 3.277, 3.346, 3.415,
       3.484, 3.553, 3.622, 3.691, 3.76 , 3.829, 3.898, 3.967, 4.036,
       4.105, 4.174, 4.243, 4.312, 4.381, 4.45 , 4.519, 4.588, 4.657,
       4.726, 4.795, 4.864, 4.933])

* Menggunakan metode around untuk membulatkan elemen ke 1 angka diblakang koma. 

In [192]:
a56 = np.around (a5_, 1)
a56

array([1. , 1.1, 1.1, 1.2, 1.3, 1.3, 1.4, 1.5, 1.6, 1.6, 1.7, 1.8, 1.8,
       1.9, 2. , 2. , 2.1, 2.2, 2.2, 2.3, 2.4, 2.4, 2.5, 2.6, 2.7, 2.7,
       2.8, 2.9, 2.9, 3. , 3.1, 3.1, 3.2, 3.3, 3.3, 3.4, 3.5, 3.6, 3.6,
       3.7, 3.8, 3.8, 3.9, 4. , 4. , 4.1, 4.2, 4.2, 4.3, 4.4, 4.4, 4.5,
       4.6, 4.7, 4.7, 4.8, 4.9, 4.9])

***FINISHED***