## HW Basic Programming III: Array and Other Data Types

### Sabtu, 27 November 2021

------------------------

### Kerjakan soal di bawah ini dengan tepat sesuai instruksi.  Tugas dikerjakan secara individu dikumpulkan dalam bentuk pdf dan jupyter notebook. Dikumpulkan paling lambat Selasa, 30 November 2021 pukul 23.59. Selamat mengerjakan! :)

### 1) a. Buatlah array 3 dimensi berukuran 3x8 yang berisi elemen bilangan 0 sampai 23 secara terurut! Beri nama arr1 dan tampilkan elemen-elemennya!

In [303]:
#Tulis kode kamu di sini, tekan Shift + Enter untuk execute
#Disclaimer: Makin singkat dan simple kodemu makin bagus dan efisien
import numpy as np

arr1 = np.array([[0,1,2,3,4,5,6,7],[8,9,10,11,12,13,14,15],[16,17,18,19,20,21,22,23]])
print(arr1)
print (type(arr1))


[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
<class 'numpy.ndarray'>


In [304]:
arr1 = np.arange(24).reshape(3,8)
print (arr1)
print(type(arr1))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
<class 'numpy.ndarray'>


### b. Tambahkan elemen berikut [24, 25, 26, 27, 28, 29, 30, 31] pada array arr1 di atas sehingga array baru bernama arr2 adalah array berukuran berukuran 4x8. Tampilkan array baru tersebut!

In [305]:
#Tulis kode kamu di sini, tekan Shift + Enter untuk execute

a = np.array([24,25,26,27,28,29,30,31])
arr2 = (np.append(arr1,([a]),axis=0))
print (arr2)
print (type(arr2))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
<class 'numpy.ndarray'>


### 3) Gabung arr1 dan arr2 sehingga menjadi arr3 yang merupakan array berukuran 7x8. Tampilkan arr3 tersebut!

In [306]:
#Tulis kode kamu di sini, tekan Shift + Enter untuk execute
arr3 = (np.concatenate((arr1,arr2),axis = 0))
print (arr3)
print (type(arr3))

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
<class 'numpy.ndarray'>


### 4) Ubah ukuran arr3 menjadi array dengan 4 kolom dan 14 baris

In [307]:
a = np.array([arr3]).reshape(14,4)
print (a)
print (type(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
<class 'numpy.ndarray'>


### 2) Di bawah ini  ada sebuah array yang berisi elemen berupa nomor urut peserta pada sebuah "SLICE GAME". Lakukan ekstraksi elemen-elemen untuk array tersebut menggunakan slicing untuk mengiris setiap nomor urut berikut!

In [6]:
#Tekan Shift + Enter untuk execute syntax ini
import numpy as np
slice_game = np.array([[121, 232,343, 454], [565,676,787,898],[989,878,767,656],
                [545,434,323,212]])
print(slice_game)
print(type(slice_game))

[[121 232 343 454]
 [565 676 787 898]
 [989 878 767 656]
 [545 434 323 212]]
<class 'numpy.ndarray'>


### a. Nomor urut 212 harus diambil dari Slice Game. Eksekusi dia!

In [7]:
#Tulis kode kamu di sini, tekan Shift + Enter untuk execute
slice_game [3,3]

212

### b. Ganti nomor urut 212 tersebut dengan nomor 456 . Cek nomor urut semua peserta SLICE GAME dengan menampilkan semua elemennya!

In [8]:
#Tulis kode kamu di sini, tekan Shift + Enter untuk execute
slice_game [3,3] = 456
print(slice_game)
print (type(slice_game))

[[121 232 343 454]
 [565 676 787 898]
 [989 878 767 656]
 [545 434 323 456]]
<class 'numpy.ndarray'>


### c. Ambil nomor urut peserta pada semua baris ke-1 dan baris ke-3 secara langsung, karena mereka harus bertanding dalam SLICE GAME.

In [9]:
#Tulis kode kamu di sini, tekan Shift + Enter untuk execute
slice_game [0:3:2]

array([[121, 232, 343, 454],
       [989, 878, 767, 656]])

### d. Ubah formasi SLICE GAME dimana nomor 565 ada pada nomor urut kedua dan 656 menjadi nomor urut kedua terakhir!

In [10]:
#Tulis kode kamu di sini, tekan Shift + Enter untuk execute
slice_game [0,1]= 565
slice_game [1,0]= 232
slice_game [3,2]= 656
slice_game [2,3]= 323

print(slice_game)
print (type(slice_game))


[[121 565 343 454]
 [232 676 787 898]
 [989 878 767 323]
 [545 434 656 456]]
<class 'numpy.ndarray'>


### e. Bagilah peserta SLICE GAME menjadi 2 tim, golongan kanan dan golongan kiri.  Kedua tim tersebut ada dalam sebuah variabel bernama *team_slice_game*. Tampilkan kedua tim tersebut!

In [11]:
#Tulis kode kamu di sini, tekan Shift + Enter untuk execute
c = slice_game
d = np.hsplit(c,2)
print (d)


[array([[121, 565],
       [232, 676],
       [989, 878],
       [545, 434]]), array([[343, 454],
       [787, 898],
       [767, 323],
       [656, 456]])]


In [13]:
c = slice_game 
e = np.vsplit(c,2)
print (e,d)

[array([[121, 565, 343, 454],
       [232, 676, 787, 898]]), array([[989, 878, 767, 323],
       [545, 434, 656, 456]])] [array([[121, 565],
       [232, 676],
       [989, 878],
       [545, 434]]), array([[343, 454],
       [787, 898],
       [767, 323],
       [656, 456]])]


### 3) Buatlah sebuah perulangan (loop) yang mampu menelusuri setiap elemen array kemudian print elemen tersebut.
Output haruslah dalam bentuk angka kembar 1 1, 2 2, dst sampai 8 8.

In [329]:
#Tulis kode kamu di sini, tekan Shift + Enter untuk execute

arr = np.array([1,2,3,4,5,6,7,8])
for i in arr:
    print (i,i)
    

1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8


### 4) Buatlah array berukuran 1X100 yang berisi elemen 0 - 99. Kemudian lakukan data type conversion elemen array tersebut menjadi tipe data string. Tampilkan semua elemen array tersebut!

In [330]:
#Tulis kode kamu di sini, tekan Shift + Enter untuk execute
x = np.arange(100).reshape(1,100)
print (x)
print (type(x))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
  72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
  96 97 98 99]]
<class 'numpy.ndarray'>


In [331]:
u = x.astype(np.str)
print (u)
print (type(u))

[['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
  '16' '17' '18' '19' '20' '21' '22' '23' '24' '25' '26' '27' '28' '29'
  '30' '31' '32' '33' '34' '35' '36' '37' '38' '39' '40' '41' '42' '43'
  '44' '45' '46' '47' '48' '49' '50' '51' '52' '53' '54' '55' '56' '57'
  '58' '59' '60' '61' '62' '63' '64' '65' '66' '67' '68' '69' '70' '71'
  '72' '73' '74' '75' '76' '77' '78' '79' '80' '81' '82' '83' '84' '85'
  '86' '87' '88' '89' '90' '91' '92' '93' '94' '95' '96' '97' '98' '99']]
<class 'numpy.ndarray'>


<ipython-input-331-d7aaa399db52>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  u = x.astype(np.str)


# Finished